FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install prisma --production

COPY . .

RUN npm install

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]
