version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - reservation-network

  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/reservation_db"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - reservation-network

networks:
  reservation-network:
    driver: bridge

volumes:
  postgres-data:
